const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.List,
		C3.Plugins.TextBox,
		C3.Plugins.Json,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.Shape3D,
		C3.Plugins.Mikal_3DObject,
		C3.Behaviors.MoveTo,
		C3.Plugins.Arr,
		C3.Plugins.CV_PlayFabClient_Leaderboards,
		C3.Plugins.CV_PlayFabClient_APIModule,
		C3.Plugins.CV_PlayFabClient_Authentication,
		C3.Plugins.Spritefont2,
		C3.Plugins.Date,
		C3.Plugins.CV_PlayFabClient_AccountManager,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Audio.Exps.Duration,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.ScriptsInEvents.Gamesheet_Event30_Act1,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Camera3D.Exps.LayerToLayerY,
		C3.Plugins.TiledBg.Exps.BBoxMidX,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Plugins.TiledBg.Exps.ZElevation,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.TiledBg.Exps.ImageScaleX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Shape3D.Cnds.CompareY,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Acts.SetOpacity,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Shape3D.Acts.SetZHeight,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Shape3D.Exps.UID,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickNthChild,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.ChangeTags,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.Mikal_3DObject.Exps.ZAngle,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Mikal_3DObject.Acts.SetZElevation,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.NinePatch.Cnds.CompareY,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.NinePatch.Cnds.HasTags,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.Mikal_3DObject.Cnds.CompareY,
		C3.Plugins.Mikal_3DObject.Exps.UID,
		C3.Plugins.Shape3D.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.NinePatch.Exps.ZElevation,
		C3.Plugins.NinePatch.Acts.MoveToBottom,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.ScriptsInEvents.Gamesheet_Event161_Act5,
		C3.ScriptsInEvents.Gamesheet_Event161_Act6,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.ScriptsInEvents.Gamesheet_Event173,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.rgbex255,
		C3.ScriptsInEvents.Gamesheet_Event176,
		C3.ScriptsInEvents.Gamesheet_Event179,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.Shape3D.Acts.SetDefaultColor,
		C3.Plugins.Shape3D.Cnds.PickByUID,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Shape3D.Acts.SetX,
		C3.Plugins.Camera3D.Exps.CameraX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Camera3D.Exps.CameraY,
		C3.Plugins.Camera3D.Exps.CameraZ,
		C3.Plugins.Camera3D.Exps.LookX,
		C3.Plugins.Camera3D.Exps.LookY,
		C3.Plugins.Camera3D.Exps.LookZ,
		C3.Plugins.Camera3D.Exps.UpX,
		C3.Plugins.Camera3D.Exps.UpY,
		C3.Plugins.Camera3D.Exps.UpZ,
		C3.Plugins.Mikal_3DObject.Cnds.PickByUID,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Behaviors.Tween.Acts.SetTweensPlaybackRate,
		C3.Behaviors.Tween.Exps.PlaybackRate,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Mikal_3DObject.Acts.SetRotationOrdered,
		C3.Plugins.Mikal_3DObject.Exps.XAngle,
		C3.Plugins.Mikal_3DObject.Exps.YAngle,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.ScriptsInEvents.Gamesheet_Event243_Act5,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.ScriptsInEvents.Gamesheet_Event244_Act4,
		C3.ScriptsInEvents.Gamesheet_Event246_Act4,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.ScriptsInEvents.Gamesheet_Event273_Act5,
		C3.ScriptsInEvents.Gamesheet_Event274_Act4,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.ScriptsInEvents.Gamesheet_Event278_Act4,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.ScriptsInEvents.Gamesheet_Event281_Act3,
		C3.ScriptsInEvents.Loadersheet_Event2_Act1,
		C3.ScriptsInEvents.Loadersheet_Event2_Act2,
		C3.Plugins.Json.Acts.Parse,
		C3.ScriptsInEvents.Loadersheet_Event8_Act12,
		C3.ScriptsInEvents.Loadersheet_Event13_Act2,
		C3.ScriptsInEvents.Loadersheet_Event14_Act6,
		C3.ScriptsInEvents.Loadersheet_Event16_Act1,
		C3.Plugins.System.Exps.loadingprogress,
		C3.ScriptsInEvents.Loadersheet_Event18_Act2,
		C3.ScriptsInEvents.Homesheet_Event2_Act1,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.TiledBg.Cnds.HasTags,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Mouse.Exps.WheelDeltaY,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Exps.Speed,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.ScriptsInEvents.Homesheet_Event67_Act1,
		C3.ScriptsInEvents.Homesheet_Event73_Act1,
		C3.Plugins.Sprite.Cnds.PickNthChild,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Exps.layoutname,
		C3.ScriptsInEvents.Generalsheet_Event4_Act1,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Arr.Exps.Count,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Behaviors.Tween.Cnds.OnTweensLoop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.SetTimescale,
		C3.ScriptsInEvents.Generalsheet_Event116_Act3,
		C3.ScriptsInEvents.Generalsheet_Event126_Act3,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.ScriptsInEvents.Generalsheet_Event151_Act1,
		C3.ScriptsInEvents.Generalsheet_Event179_Act2,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Acts.GetLeaderboardAroundPlayer,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Acts.AddStatisticUpdateStack,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Acts.UpdatePlayerStatistics,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Cnds.OnUpdatePlayerStatistics,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Exps.ServerResponse,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Cnds.OnGetLeaderboard,
		C3.Plugins.CV_PlayFabClient_Leaderboards.Acts.GetLeaderboard,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.CV_PlayFabClient_Authentication.Acts.CustomIDLogin,
		C3.Plugins.CV_PlayFabClient_Authentication.Cnds.CustomIDLogin_AccountNotFound,
		C3.Plugins.CV_PlayFabClient_Authentication.Cnds.CustomIDLogin,
		C3.Plugins.CV_PlayFabClient_AccountManager.Acts.UpdateUserTitleDisplayName,
		C3.Plugins.CV_PlayFabClient_Authentication.Cnds.CustomIDLogin_Error,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Plugins.List.Acts.SetBlur,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.List.Exps.SelectedText,
		C3.ScriptsInEvents.Levelcreatorsheet_Event3_Act2,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.TextBox.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{StartW: 0},
	{StartH: 0},
	{Clickable: 0},
	{BtnClose: 0},
	{BtnDoonDookStudio: 0},
	{BtnInfo: 0},
	{BtnMusic: 0},
	{BtnLevelMode: 0},
	{BtnSFX: 0},
	{Reward: 0},
	{BtnWatchAd: 0},
	{BtnPause: 0},
	{BtnResume: 0},
	{BtnHome: 0},
	{BtnReset: 0},
	{BtnBuyBall: 0},
	{BtnBack: 0},
	{BtnShop: 0},
	{BtnEndlessMode: 0},
	{BtnPlayMusic: 0},
	{DifficultyLevel: 0},
	{BtnDiffulty: 0},
	{BtnLeaderboard: 0},
	{BtnPrivacyOk: 0},
	{BtnPrivacy: 0},
	{TxtInfo: 0},
	{TxtBtnPlay: 0},
	{TxtRv: 0},
	{Num: 0},
	{Timer: 0},
	{TxtRvTimer: 0},
	{TxtRv2: 0},
	{TxtScore: 0},
	{TxtGeneral: 0},
	{TxtItem: 0},
	{Tween: 0},
	{TxtNotEnoghDiamond: 0},
	{MusicFullName: 0},
	{TxtMusicName: 0},
	{TxtBallPrice: 0},
	{TxtLevelDoneScore: 0},
	{TxtBestScore: 0},
	{TxtNeededAd: 0},
	{TxtBestScoreHome: 0},
	{TxtLBTitle: 0},
	{TxtLBMessage: 0},
	{TxtPrivacy: 0},
	{PUp_LevelDone: 0},
	{PUp_GameOver: 0},
	{PUp_Pause: 0},
	{PUp_Info: 0},
	{PUp_MusicDifficulty: 0},
	{Pup_MusicList: 0},
	{Pup_Privacy: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{"3DCamera": 0},
	{Mouse: 0},
	{List_Music: 0},
	{TextInput: 0},
	{JSON_Config: 0},
	{JSON_LS: 0},
	{JSON_Beatmap: 0},
	{JSON_LB: 0},
	{JSON_SignIn: 0},
	{AdCountDown: 0},
	{Title: 0},
	{Ground: 0},
	{JumpedOn: 0},
	{MusicTime: 0},
	{Tile: 0},
	{TileBoarder: 0},
	{TrapTile: 0},
	{GroundEdge: 0},
	{Speed: 0},
	{Scale: 0},
	{Bullet: 0},
	{Rotate: 0},
	{ParticlesConfetti: 0},
	{BallNum: 0},
	{BallIconBg: 0},
	{BestScoreIcon: 0},
	{CollectableIcon: 0},
	{LockIcon: 0},
	{Difficulty: 0},
	{MusicDifficultyUnlocked: 0},
	{NewUnlocked: 0},
	{SelectedBallBg: 0},
	{Shine: 0},
	{ShopBallLight: 0},
	{ShopStage: 0},
	{TickIcon: 0},
	{Sine: 0},
	{TutFinger: 0},
	{Effect_Ball: 0},
	{Effect_Tile: 0},
	{StartZ: 0},
	{"3D_Ball": 0},
	{"3D_GameElements": 0},
	{"3D_CollectableItem": 0},
	{"3D_Tile": 0},
	{Type: 0},
	{Tex_Sides0: 0},
	{BallFrame: 0},
	{Tex_Ball: 0},
	{Tex_Sides1: 0},
	{Tex_Sides2: 0},
	{Tex_Sides3: 0},
	{Tex_Sides4: 0},
	{Tex_Sides5: 0},
	{Tex_Sides6: 0},
	{Tex_Tile: 0},
	{GameTimer: 0},
	{MoveTo: 0},
	{TileMover: 0},
	{SpdMultiplier: 0},
	{MusicSyncer: 0},
	{Array_Temp: 0},
	{Swiper: 0},
	{Scroll: 0},
	{PosFixer: 0},
	{InvisiblePanel: 0},
	{MusicNum: 0},
	{MusicBtnBg: 0},
	{BgEffect: 0},
	{Bg_Bottom: 0},
	{Bg_Home: 0},
	{Bg_Top: 0},
	{BlackBg: 0},
	{ShopBg: 0},
	{Leaderboards: 0},
	{PlayFabAPI: 0},
	{Authentication: 0},
	{Index: 0},
	{LBBox: 0},
	{LBBoxMini: 0},
	{MaxWidth: 0},
	{MaxScale: 0},
	{TxtLBName: 0},
	{TxtLBPosition: 0},
	{txtLBMsg: 0},
	{TxtLBScore: 0},
	{TxtLbPos: 0},
	{LbPosBg: 0},
	{LeaderboardLoadingSpinner: 0},
	{BtnCrazyGames: 0},
	{BlackPanel: 0},
	{txtTitle: 0},
	{Date: 0},
	{AccountManager: 0},
	{FButtons: 0},
	{FPopup: 0},
	{FTile: 0},
	{FTex_Slides: 0},
	{FTxt: 0},
	{LookX: 0},
	{LookY: 0},
	{LookZ: 0},
	{CamX: 0},
	{CamY: 0},
	{CamZ: 0},
	{vSpd: 0},
	{GameMode: 0},
	{GameSpd: 0},
	{GameSpdRate: 0},
	{TileHeight: 0},
	{FirstTileY: 0},
	{CurColor: 0},
	{Score: 0},
	{BallCanJump: 0},
	{Horizontal_Interval: 0},
	{Trap_Interval: 0},
	{Movable_Interval: 0},
	{Horizontal_Step: 0},
	{Trap_Step: 0},
	{Movable_Step: 0},
	{Horizontal_Duration: 0},
	{Trap_Duration: 0},
	{Movable_Duration: 0},
	{Collectable_Interval: 0},
	{Collectable_Step: 0},
	{Collectable_Duration: 0},
	{LoopStarted: 0},
	{CurSongIndex: 0},
	{DiffMusic: 0},
	{DifficultyVal: 0},
	{StepToActiveFreeBalls: 0},
	{InitGameLayers: 0},
	{vSidesSpawnDelay: 0},
	{vFirstSide: 0},
	{vFrame: 0},
	{vType: 0},
	{vSide: 0},
	{isVertical: 0},
	{vMovable: 0},
	{vTrapTileID: 0},
	{vPosX: 0},
	{vPosY: 0},
	{vWidth: 0},
	{vHieght: 0},
	{vMaxTileCount: 0},
	{vCurSpawnY: 0},
	{vCurSpawnX: 0},
	{vTime: 0},
	{vTileID: 0},
	{vMinJump: 0},
	{vMaxJump: 0},
	{vMaxTileDistance: 0},
	{vCurVerticalTlie: 0},
	{vBallEffectSize: 0},
	{vCanShowLevelDone: 0},
	{vPrtcSpeedRight: 0},
	{vPrtcSpeedLeft: 0},
	{vPrtcAngleRight: 0},
	{vPrtcAngleLeft: 0},
	{vRnd: 0},
	{Dir: 0},
	{Ang: 0},
	{R: 0},
	{G: 0},
	{B: 0},
	{HEXColor: 0},
	{vDarkness: 0},
	{vLightness: 0},
	{vObj: 0},
	{vID: 0},
	{vStartTouchX: 0},
	{vTouchDX: 0},
	{vCamDX: 0},
	{vCamMoveXTime: 0},
	{vNum: 0},
	{Val: 0},
	{vDifficulty: 0},
	{vDifficultyLevel: 0},
	{vMusicFileName: 0},
	{vMusicNum: 0},
	{vTS: 0},
	{Paused: 0},
	{vRandID: 0},
	{LS_KEY: 0},
	{LS_KEY_Data: 0},
	{CrazyLoaded: 0},
	{loadStarted: 0},
	{STATISTIC_NAME: 0},
	{InitHomeLayers: 0},
	{SpdReduceRate: 0},
	{SwipeMaxSpd: 0},
	{MinSwipeY: 0},
	{MaxSwipeY: 0},
	{DY: 0},
	{StartTouchX: 0},
	{StartTouchY: 0},
	{EndTouchY: 0},
	{ThumbScrolling: 0},
	{WheelScrolling: 0},
	{MaxMusicNameLength: 0},
	{Rows: 0},
	{Cols: 0},
	{vCols: 0},
	{TopDistance: 0},
	{HorSpc: 0},
	{VerSpc: 0},
	{InitX: 0},
	{InitY: 0},
	{vLeft: 0},
	{vRight: 0},
	{vTop: 0},
	{vBottom: 0},
	{vTouchSpeed: 0},
	{Y: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{MusicFileName: 0},
	{MusicVol: 0},
	{ClickedButton: 0},
	{CurLayer: 0},
	{AdState: 0},
	{JustRegistered: 0},
	{PlayerSet: 0},
	{LBPlayerPos: 0},
	{LBPlayerScore: 0},
	{LBTryTIme: 0},
	{HasAdblocker: 0},
	{Exceptions: 0},
	{Which: 0},
	{Do: 0},
	{AfterClose: 0},
	{Name: 0},
	{Volume: 0},
	{vAction: 0},
	{error: 0},
	{Action: 0},
	{Value: 0},
	{vIndex: 0},
	{vCurPosition: 0},
	{vCurName: 0},
	{vCurScore: 0},
	{vLastIndex: 0},
	{PlayerSet2: 0},
	{User: 0},
	{vMusicName: 0}
];

self.InstanceType = {
	BtnClose: class extends self.ISpriteInstance {},
	BtnDoonDookStudio: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnLevelMode: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnWatchAd: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnResume: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnBuyBall: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnShop: class extends self.ISpriteInstance {},
	BtnEndlessMode: class extends self.ISpriteInstance {},
	BtnPlayMusic: class extends self.ISpriteInstance {},
	BtnDiffulty: class extends self.ISpriteInstance {},
	BtnLeaderboard: class extends self.ISpriteInstance {},
	BtnPrivacyOk: class extends self.ISpriteInstance {},
	BtnPrivacy: class extends self.ISpriteInstance {},
	TxtInfo: class extends self.ITextInstance {},
	TxtBtnPlay: class extends self.ITextInstance {},
	TxtRv: class extends self.ITextInstance {},
	TxtRvTimer: class extends self.ITextInstance {},
	TxtRv2: class extends self.ITextInstance {},
	TxtScore: class extends self.ITextInstance {},
	TxtGeneral: class extends self.ITextInstance {},
	TxtItem: class extends self.ITextInstance {},
	TxtNotEnoghDiamond: class extends self.ITextInstance {},
	TxtMusicName: class extends self.ITextInstance {},
	TxtBallPrice: class extends self.ITextInstance {},
	TxtLevelDoneScore: class extends self.ITextInstance {},
	TxtBestScore: class extends self.ITextInstance {},
	TxtNeededAd: class extends self.ITextInstance {},
	TxtBestScoreHome: class extends self.ITextInstance {},
	TxtLBTitle: class extends self.ITextInstance {},
	TxtLBMessage: class extends self.ITextInstance {},
	TxtPrivacy: class extends self.ITextInstance {},
	PUp_LevelDone: class extends self.IWorldInstance {},
	PUp_GameOver: class extends self.IWorldInstance {},
	PUp_Pause: class extends self.IWorldInstance {},
	PUp_Info: class extends self.IWorldInstance {},
	PUp_MusicDifficulty: class extends self.IWorldInstance {},
	Pup_MusicList: class extends self.IWorldInstance {},
	Pup_Privacy: class extends self.IWorldInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	_3DCamera: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	List_Music: class extends self.IListInstance {},
	TextInput: class extends self.ITextInputInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	JSON_Beatmap: class extends self.IJSONInstance {},
	JSON_LB: class extends self.IJSONInstance {},
	JSON_SignIn: class extends self.IJSONInstance {},
	AdCountDown: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Tile: class extends self.IWorldInstance {},
	TileBoarder: class extends self.IWorldInstance {},
	TrapTile: class extends self.IWorldInstance {},
	GroundEdge: class extends self.IWorldInstance {},
	ParticlesConfetti: class extends self.ISpriteInstance {},
	BallIconBg: class extends self.IWorldInstance {},
	BestScoreIcon: class extends self.ISpriteInstance {},
	CollectableIcon: class extends self.ISpriteInstance {},
	LockIcon: class extends self.ISpriteInstance {},
	MusicDifficultyUnlocked: class extends self.ISpriteInstance {},
	SelectedBallBg: class extends self.IWorldInstance {},
	Shine: class extends self.ISpriteInstance {},
	ShopBallLight: class extends self.ISpriteInstance {},
	ShopStage: class extends self.ISpriteInstance {},
	TickIcon: class extends self.ISpriteInstance {},
	TutFinger: class extends self.ISpriteInstance {},
	Effect_Ball: class extends self.ISpriteInstance {},
	Effect_Tile: class extends self.IWorldInstance {},
	_3D_Ball: class extends self.I3DShapeInstance {},
	_3D_GameElements: class extends self.I3DShapeInstance {},
	_3D_CollectableItem: class extends self.IWorldInstance {},
	_3D_Tile: class extends self.I3DShapeInstance {},
	Tex_Sides0: class extends self.ISpriteInstance {},
	BallFrame: class extends self.ISpriteInstance {},
	Tex_Ball: class extends self.ISpriteInstance {},
	Tex_Sides1: class extends self.ISpriteInstance {},
	Tex_Sides2: class extends self.ISpriteInstance {},
	Tex_Sides3: class extends self.ISpriteInstance {},
	Tex_Sides4: class extends self.ISpriteInstance {},
	Tex_Sides5: class extends self.ISpriteInstance {},
	Tex_Sides6: class extends self.ISpriteInstance {},
	Tex_Tile: class extends self.IWorldInstance {},
	GameTimer: class extends self.ISpriteInstance {},
	TileMover: class extends self.ISpriteInstance {},
	SpdMultiplier: class extends self.ISpriteInstance {},
	MusicSyncer: class extends self.ISpriteInstance {},
	Array_Temp: class extends self.IArrayInstance {},
	Swiper: class extends self.ISpriteInstance {},
	Scroll: class extends self.ISpriteInstance {},
	PosFixer: class extends self.ISpriteInstance {},
	InvisiblePanel: class extends self.ITiledBackgroundInstance {},
	MusicBtnBg: class extends self.IWorldInstance {},
	BgEffect: class extends self.ISpriteInstance {},
	Bg_Bottom: class extends self.ITiledBackgroundInstance {},
	Bg_Home: class extends self.ITiledBackgroundInstance {},
	Bg_Top: class extends self.ITiledBackgroundInstance {},
	BlackBg: class extends self.ITiledBackgroundInstance {},
	ShopBg: class extends self.ITiledBackgroundInstance {},
	Leaderboards: class extends self.IInstance {},
	PlayFabAPI: class extends self.IInstance {},
	Authentication: class extends self.IInstance {},
	LBBox: class extends self.IWorldInstance {},
	LBBoxMini: class extends self.IWorldInstance {},
	TxtLBName: class extends self.ITextInstance {},
	TxtLBPosition: class extends self.ITextInstance {},
	txtLBMsg: class extends self.ISpriteFontInstance {},
	TxtLBScore: class extends self.ITextInstance {},
	TxtLbPos: class extends self.ISpriteFontInstance {},
	LbPosBg: class extends self.ISpriteInstance {},
	LeaderboardLoadingSpinner: class extends self.ISpriteInstance {},
	BtnCrazyGames: class extends self.ISpriteInstance {},
	BlackPanel: class extends self.IWorldInstance {},
	txtTitle: class extends self.ISpriteFontInstance {},
	Date: class extends self.IInstance {},
	AccountManager: class extends self.IInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FPopup: class extends self.IWorldInstance {},
	FTile: class extends self.IWorldInstance {},
	FTex_Slides: class extends self.ISpriteInstance {},
	FTxt: class extends self.ITextInstance {}
}