'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/CMP_FILE?referer=yandex.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #206dc5 !important; "
+"   border-color: #206dc5 !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #206dc5 !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #206dc5 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #206dc5 !important; "
+"   border-color: #206dc5 !important; "
+" } "
+" .qc-cmp-button { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #206dc5 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #ffffff !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui, "
+" .qc-cmp-ui .qc-cmp-title, "
+" .qc-cmp-ui .qc-cmp-table, "
+" .qc-cmp-ui .qc-cmp-messaging, "
+" .qc-cmp-ui .qc-cmp-sub-title, "
+" .qc-cmp-ui .qc-cmp-vendor-list, "
+" .qc-cmp-ui .qc-cmp-purpose-info, "
+" .qc-cmp-ui .qc-cmp-table-header, "
+" .qc-cmp-ui .qc-cmp-beta-messaging, "
+" .qc-cmp-ui .qc-cmp-main-messaging, "
+" .qc-cmp-ui .qc-cmp-vendor-list-title{ "
+"   color: #141E23 !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #206dc5 !important; "
+" } "
+" .qc-cmp-ui { "
+"   background-color: #ffffff !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #206dc5!important; "
+"   border-color: #206dc5!important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"uspVersion":1,"uspJurisdiction":["CA"],"uspLspact":"N","siteUuid":"21585260-c2dc-4e66-b0a4-6e0de07c7bbb","themeUuid":"95f46183-fd64-4686-a897-34a11363ce81","uspPrivacyPolicyLink":"https://yandex.com/legal/confidential/en/","uspDeleteDataLink":"https://yandex.com/support/games/en/feedback","uspAccessDataLink":"https://yandex.com/support/games/en/feedback","suppressCcpaLinks":false,"inmobiAccountId":"DyVXqQCBu6JSN","privacyMode":["GDPR","USP"],"gdprEncodingMode":"TCF_AND_GPP","mspaJurisdiction":"STATE_AND_NATIONAL","isCoveredTransaction":false,"mspaSignalMode":"OPT_OUT","ccpaViaUsp":false,"mspaOptOutPurposeIds":[1,2,3,4],"consentLocations":["EEA","USA","BRAZIL","CANADA"],"mspaAutoPopUp":false,"includeVendorsDisclosedSegment":true,"cmpVersion":"latest","hashCode":"TAuFUWHiwTLHudbygaYtGQ","publisherCountryCode":"AE","publisherName":"Yandex","vendorPurposeIds":[1,2,3,4,5,6,7,8,9,10,11],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2,3],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"always","defaultToggleValue":"off","initScreenRejectButtonShowing":false,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":true,"uiLayout":"banner","vendorListUpdateFreq":30,"publisherPurposeIds":[1,2,3,4,5],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[1,42],"lang_":"en","gvlVersion":3,"totalVendors":1025,"gbcConfig":{"enabled":true,"urlPassThrough":false,"adsDataRedaction":false,"locations":["EEA"],"applicablePurposes":[{"id":1,"defaultValue":"DENIED"},{"id":2,"defaultValue":"DENIED"},{"id":3,"defaultValue":"DENIED"},{"id":4,"defaultValue":"DENIED"},{"id":5,"defaultValue":"DENIED"},{"id":6,"defaultValue":"DENIED"},{"id":7,"defaultValue":"DENIED"}]},"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/DyVXqQCBu6JSN/95f46183-fd64-4686-a897-34a11363ce81/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/DyVXqQCBu6JSN/95f46183-fd64-4686-a897-34a11363ce81/${language}.json"},"gdprEnabledInUS":false,"optOutFromAllEnabled":false},"premiumUiLabels":{"uspDnsText":[""],"uspPrivacyPolicyLinkText":"Privacy Policy","uspDeleteDataLinkText":"Delete my data","uspAccessDataLinkText":"Access my data"},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{"initScreenRejectButton":"DISAGREE","saveAndExitButton":"SAVE & EXIT","agreeButton":"AGREE"},"theme":{"uxPrimaryButtonTextColor":"#ffffff","uxPrimaryButtonColor":"#206dc5","uxBackgroundColor":"#ffffff","uxSecondaryButtonColor":"#ffffff","uxSecondaryButtonTextColor":"#206dc5","uxToogleActiveColor":"#206dc5","uxLinkColor":"#206dc5","uxFontColor":"#141E23"},"nonIabVendorsInfo":{}});})();