lang_data = {};

lang_data.en = {
    head_start: "Headstart",
    x2_coins: "Double stars",
    buyed: "Bought",
    perfect: "Perfect!",
    great: "Great!",
    tap_to_head_start: "Tap to use Head Start",
    new_record: "NEW RECORD",
    pause: "Pause",
    continue_for: "Continue for",
    locked: "Locked",
    result: "RESULT",
    record: "RECORD",
    earn_coins: "Earn * stars",
    thx_for_watching: "Thanks for watching",
    thx: "Thank you!",
    watched_all: "You watched all available videos for now.",
    back_later: "Come back later!",
    reward: "Reward",
    not_coins: "Not enough stars"
}, 

lang_data.de = {
    head_start: "Vorsprung",
    x2_coins: "Doppelte Sterne",
    buyed: "Gekauft",
    perfect: "Perfekt!!",
    great: "Toll!!",
    tap_to_head_start: "Tippen, um Vorsprung zu nutzen",
    new_record: "NEUER REKORD",
    pause: "Pause",
    continue_for: "Weiter für",
    locked: "Gesperrt",
    result: "ERGEBNIS",
    record: "REKORD",
    earn_coins: "Verdiene * Sterne",
    thx_for_watching: "Danke für's Ansehen",
    thx: "Danke!",
    watched_all: "Du hast alle momentan verfügbaren Videos gesehen.",
    back_later: "Komm später wieder!",
    reward: "Belohnung",
    not_coins: "Nicht genügend Sterne"
}, 

lang_data.es = {
    head_start: "Ventaja inicial",
    x2_coins: "Estrellas dobles",
    buyed: "Comprado",
    perfect: "¡Perfecto!",
    great: "¡Magnífico!",
    tap_to_head_start: "Toca para usar la Ventaja inicial",
    new_record: "RÉCORD NUEVO",
    pause: "Pausa",
    continue_for: "Continuar para",
    locked: "Bloqueado",
    result: "RESULTADO",
    record: "RÉCORD",
    earn_coins: "Gana * estrellas",
    thx_for_watching: "Gracias por ver el vídeo",
    thx: "¡Gracias!",
    watched_all: "Has visto todos los vídeos disponibles por ahora.",
    back_later: "¡Vuelve pronto!",
    reward: "Recompensa",
    not_coins: "No tienes suficientes estrellas"
}, 

lang_data.fr = {
    head_start: "Bon départ",
    x2_coins: "Étoiles doubles",
    buyed: "Acheté",
    perfect: "Parfait!",
    great: "Génial!",
    tap_to_head_start: "Appuyer pour utiliser le Bon départ",
    new_record: "NOUVEL ENREGISTREMENT",
    pause: "Pause",
    continue_for: "Continuer",
    locked: "Verrouillé",
    result: "RÉSULTAT",
    record: "RECORD",
    earn_coins: "Gagne * étoiles",
    thx_for_watching: "Gagne * étoiles",
    thx: "Je te remercie !",
    watched_all: "Tu as regardé toutes les vidéos disponibles pour le moment.",
    back_later: "Reviens plus tard !",
    reward: "Récompense",
    not_coins: "Pas assez d'étoiles"
}, 


lang_data.pt = {
    head_start: "Avanço",
    x2_coins: "Estrelas duplas",
    buyed: "Comprado",
    perfect: "Perfeito!",
    great: "Excelente!",
    tap_to_head_start: "Toca para usar Vantagem",
    new_record: "NOVO RECORDE",
    pause: "Pausa",
    continue_for: "Continuar para",
    locked: "Bloqueado",
    result: "RESULTADO",
    record: "RECORDE",
    earn_coins: "Ganha * estrelas",
    thx_for_watching: "Obrigado por veres",
    thx: "Obrigado!",
    watched_all: "Viste todos os vídeos disponíveis de momento.",
    back_later: "Volta mais tarde!",
    reward: "Recompensa",
    not_coins: "Sem estrelas suficientes"
}, 

lang_data.it = {
    head_start: "Vantaggio",
    x2_coins: "Raddoppia le stelle",
    buyed: "Comprato",
    perfect: "Perfetto!",
    great: "Fantastico!",
    tap_to_head_start: "Tocca per utilizzare il Vantaggio",
    new_record: "NUOVO RECORD",
    pause: "Pausa",
    continue_for: "Continua per",
    locked: "Bloccato",
    result: "RISULTATO",
    record: "RECORD",
    earn_coins: "Guadagna * stelle",
    thx_for_watching: "Grazie per aver visualizzato",
    thx: "Grazie!",
    watched_all: "Hai guardato tutti i video disponibili al momento.",
    back_later: "Ritorna in seguito!",
    reward: "Ricompensa",
    not_coins: "Non hai abbastanza stelle"
}, 

lang_data.tr = {
    head_start: "Önde Başlama",
    x2_coins: "Çifte yıldızlar",
    buyed: "Satın alınan",
    perfect: "Mükemmel!",
    great: "Harika!",
    tap_to_head_start: "Önde Başlamayı Kullanmak için Dokun",
    new_record: "YENİ REKOR",
    pause: "Duraklat",
    continue_for: "Devam Etmek için:",
    locked: "Kilitli",
    result: "SONUÇ",
    record: "REKOR",
    earn_coins: "* yıldız kazan",
    thx_for_watching: "İzlediğin için teşekkürler",
    thx: "Teşekkürler!",
    watched_all: "Şu anda mevcut olan tüm videoyu izledin.",
    back_later: "Daha sonra tekrar gel!",
    reward: "Ödül",
    not_coins: "Yeterli yıldız yok"
}, 
lang_data.ru = {
    head_start: "Суперcтарт",
    x2_coins: "Удвоитель монет",
    buyed: "Куплено",
    perfect: "Отлично!",
    great: "Идеально!",
    tap_to_head_start: "Нажмите чтобы использовать Суперстарт",
    new_record: "НОВЫЙ РЕКОРД",
    pause: "Пауза",
    continue_for: "Продолжить за",
    locked: "Заблокировано",
    result: "РЕЗУЛЬТАТ",
    record: "РЕКОРД",
    earn_coins: "Получить * звезд",
    thx_for_watching: "Спасибо за просмотр",
    thx: "Спасибо!",
    watched_all: "Вы посмотрели все видео доступные на данный момент.",
    back_later: "Пожалуйста, попробуйте позже!",
    reward: "Награда",
    not_coins: "Не хватает звезд"
};


lang_data.nl = {
    head_start: "Voorsprong bij de start",
    x2_coins: "Dubbele sterren",
    buyed: "Gekocht",
    perfect: "Perfect!",
    great: "Geweldig!",
    tap_to_head_start: "Tik om de voorsprong bij de start te gebruiken",
    new_record: "NIEUW RECORD",
    pause: "Pauze",
    continue_for: "Doorgaan voor",
    locked: "Vergrendeld",
    result: "RESULTAAT",
    record: "RECORD",
    earn_coins: "Verdien * sterren",
    thx_for_watching: "Bedankt voor het kijken",
    thx: "Dankjewel!",
    watched_all: "Je hebt alle beschikbare video’s voor nu gezien.",
    back_later: "Kom later terug!",
    reward: "Beloning",
    not_coins: "Niet genoeg sterren"
};


lang_data.pl = {
    head_start: "Ułatwienie",
    x2_coins: "Podwójne gwiazdki",
    buyed: "Zakupione",
    perfect: "Perfekcyjnie!",
    great: "Świetnie!",
    tap_to_head_start: "Stuknij, aby użyć ułatwienia",
    new_record: "NOWY REKORD",
    pause: "Pauza",
    continue_for: "Kontynuuj za",
    locked: "Zablokowane",
    result: "WYNIK",
    record: "REKORD",
    earn_coins: "Zdobądź * gwiazdek",
    thx_for_watching: "Dziękujemy za obejrzenie",
    thx: "Dziękujemy!",
    watched_all: "Obejrzałeś wszystkie dostępne teraz filmy.",
    back_later: "Zapraszamy później!",
    reward: "Nagroda",
    not_coins: "Nie masz tylu gwiazdek"
};